
version: '3'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
        gunicorn -b 0.0.0.0:5001
        --access-logfile -
        --log-level=debug
        --reload
        "flask_ab_test_example.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/app'
    ports:
      - '5001:5001'

volumes:
  redis: